### ISSUE TITLE
Crash while open

### ISSUE THREAD

**Issue by TotallyNotPooh** [itzbluebxrry/Radon-Browser#2] opened 2023-04-22 13:47 UTC

**Comment by Crusader-Boss** [comment] 2023-05-04 10:56
having the same issue. Whenever i try to open the browser it crashes and closes itself.

os: windows 10

**Comment by XCATsus** [comment] 2023-05-27 17:12
same here lol

**Comment by itzbluebxrry** [comment] 2023-06-10 04:24
Have identified the main cause of this issue, which is apparently a missing null check for localSettings values. The app crashed since there are some values which should be loaded during app launch. If you have never used Radon before, there are possibilities for the app to crash.

It's just a bit of silly mistake from my end. I need time to break from development at the moment, so I'll immediately update the app with fixes in near future.

**Comment by itzbluebxrry** [comment] 2023-08-31 06:35
Duplicate of [Issue #5 - Browser crashes when open](https://github.com/itzbluebxrry/Radon-Browser/issues/5) and solved. Please check https://github.com/itzbluebxrry/Radon-Browser/releases/tag/1.4.16_Halo_Preview for changes and fixes for this issue.

**Closed by itzbluebxrry** 2023-08-31 06:35 UTC
Labels: bug
